In [14]:
import numpy as np

In [15]:
listas = [1, 2, 3, 4, 5]

In [16]:
arr = np.array(listas)

In [17]:
arr

array([1, 2, 3, 4, 5])

In [20]:
listas = [[1, 2, 3], [4, 5, 6], [7, 9, 11]]

In [21]:
matrica = np.array(listas)

In [22]:
matrica

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  9, 11]])

In [23]:
matrica * 15

array([[ 15,  30,  45],
       [ 60,  75,  90],
       [105, 135, 165]])

In [24]:
matrica + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 19, 21]])

In [26]:
matrica

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  9, 11]])

In [25]:
matrica > 10

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [28]:
matrica[matrica > 7]

array([ 9, 11])

In [48]:
arr = np.arange(0,30,4)
arr

array([ 0,  4,  8, 12, 16, 20, 24, 28])

In [37]:
type(arr[1])

numpy.int32

In [38]:
zeros = np.zeros(11)

In [41]:
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [43]:
zeros_m = np.zeros((5,4))
zeros_m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
ones = np.ones((4,8))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [57]:
interval = np.linspace(0, 49, 50)
interval

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [59]:
istriz = np.eye(6)
istriz

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [63]:
istriz = np.eye(6, k=-3)
istriz

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.]])

### random

In [65]:
unif = np.random.rand(12)
unif

array([0.85370761, 0.97884972, 0.06801606, 0.54154682, 0.74146006,
       0.76677512, 0.28821133, 0.41696448, 0.55609496, 0.01835205,
       0.84563887, 0.89087612])

In [68]:
munif = np.random.rand(12, 2)
munif

array([[0.80854707, 0.21827993],
       [0.86018792, 0.97049734],
       [0.4500817 , 0.26120566],
       [0.49455528, 0.74330711],
       [0.58819915, 0.27525881],
       [0.65277464, 0.71113735],
       [0.5729537 , 0.61513262],
       [0.64630732, 0.61140909],
       [0.57603088, 0.54201913],
       [0.9005652 , 0.26392154],
       [0.00391845, 0.30277322],
       [0.69631949, 0.44270672]])

In [69]:
unif_n = np.random.randn(12)
unif_n

array([-0.46914083,  0.55999526, -0.34384023, -0.13865664, -1.14165392,
       -0.09621459,  0.32025859,  0.03451661,  0.02673347,  1.71647466,
       -0.92872408, -0.42957627])

In [70]:
munif_n = np.random.randn(12, 2)
munif_n

array([[ 0.28530866, -2.3352693 ],
       [-0.1555792 , -0.69742223],
       [ 0.96640333, -0.41577526],
       [-0.06961185,  0.21447384],
       [ 0.35577143, -0.55088463],
       [ 0.11857564, -1.33923679],
       [-0.30540034, -0.25526029],
       [-0.51764616,  2.38640895],
       [-0.40599756, -0.17120418],
       [-0.97524418, -1.40403602],
       [ 0.54421389,  2.2707334 ],
       [-0.07907414, -0.2707722 ]])

In [73]:
arr_int_rand = np.random.randint(10, 50, 80)
arr_int_rand

array([27, 47, 33, 35, 34, 32, 14, 23, 40, 14, 43, 11, 33, 20, 26, 38, 32,
       17, 18, 11, 15, 29, 15, 42, 14, 39, 30, 27, 18, 22, 27, 43, 26, 17,
       49, 24, 25, 15, 44, 13, 41, 12, 39, 34, 44, 40, 42, 33, 21, 24, 44,
       38, 45, 40, 17, 38, 18, 48, 25, 35, 45, 33, 12, 24, 28, 17, 20, 44,
       34, 13, 20, 39, 38, 48, 42, 29, 23, 13, 27, 16])

## masyvų formos ketimas reshape()

In [84]:
arr_int_rand.reshape(8, 10)

array([[27, 47, 33, 35, 34, 32, 14, 23, 40, 14],
       [43, 11, 33, 20, 26, 38, 32, 17, 18, 11],
       [15, 29, 15, 42, 14, 39, 30, 27, 18, 22],
       [27, 43, 26, 17, 49, 24, 25, 15, 44, 13],
       [41, 12, 39, 34, 44, 40, 42, 33, 21, 24],
       [44, 38, 45, 40, 17, 38, 18, 48, 25, 35],
       [45, 33, 12, 24, 28, 17, 20, 44, 34, 13],
       [20, 39, 38, 48, 42, 29, 23, 13, 27, 16]])

In [85]:
arr_int_rand.reshape(8, -1)

array([[27, 47, 33, 35, 34, 32, 14, 23, 40, 14],
       [43, 11, 33, 20, 26, 38, 32, 17, 18, 11],
       [15, 29, 15, 42, 14, 39, 30, 27, 18, 22],
       [27, 43, 26, 17, 49, 24, 25, 15, 44, 13],
       [41, 12, 39, 34, 44, 40, 42, 33, 21, 24],
       [44, 38, 45, 40, 17, 38, 18, 48, 25, 35],
       [45, 33, 12, 24, 28, 17, 20, 44, 34, 13],
       [20, 39, 38, 48, 42, 29, 23, 13, 27, 16]])

In [92]:
matr = arr_int_rand.reshape(-1, 8)
matr

array([[27, 47, 33, 35, 34, 32, 14, 23],
       [40, 14, 43, 11, 33, 20, 26, 38],
       [32, 17, 18, 11, 15, 29, 15, 42],
       [14, 39, 30, 27, 18, 22, 27, 43],
       [26, 17, 49, 24, 25, 15, 44, 13],
       [41, 12, 39, 34, 44, 40, 42, 33],
       [21, 24, 44, 38, 45, 40, 17, 38],
       [18, 48, 25, 35, 45, 33, 12, 24],
       [28, 17, 20, 44, 34, 13, 20, 39],
       [38, 48, 42, 29, 23, 13, 27, 16]])

In [ ]:
arr_int_rand.reshape(-1, 8) + arr_int_rand.reshape(-1, 8)

## array metodai, atributai

In [93]:
matr.min()

11

In [94]:
matr.max()

49

In [95]:
matr.argmin()

11

In [96]:
matr.argmax()

34

In [98]:
matr.shape

(10, 8)

In [99]:
matr.dtype

dtype('int32')

### indeksacija

In [102]:
s_arr = np.arange(5, 30, 3)
s_arr

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [103]:
s_arr[4]

17

In [106]:
print(s_arr[1:4])
print(s_arr[:4])
print(s_arr[1:])
print(s_arr[-3:])

[ 8 11 14]
[ 5  8 11 14]
[ 8 11 14 17 20 23 26 29]
[23 26 29]


In [107]:
l = [*range(20)]
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [111]:
arr = np.arange(0, 20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [119]:
arr[1] = 40
arr

array([ 0, 40, 66, 66, 66, 66, 66, 66,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [120]:
arr.dtype

dtype('int32')

### matricos indeksacija

In [121]:
arr_int_rand = np.random.randint(10, 2000, 40)

In [124]:
m_arr = arr_int_rand.reshape(8, -1)
m_arr

array([[1664,  675,  126,  552, 1893],
       [1122,   37, 1843, 1141,  352],
       [1477, 1582, 1154,  167,  805],
       [ 715, 1600,  114, 1461, 1388],
       [ 477,  568, 1805, 1761, 1212],
       [ 529,   41, 1575, 1806, 1177],
       [1719, 1338,  993,  444,  251],
       [ 666, 1270, 1126, 1320,  606]])

In [125]:
m_arr[4]

array([ 477,  568, 1805, 1761, 1212])

In [126]:
m_arr[4][-1]

1212

In [127]:
m_arr[4,-1]

1212

In [ ]:
m_arr[1:4, 1:3]

In [ ]:
m_arr[1:, 1:-1]

In [149]:
m_arr[2:]

array([[1477, 1582, 1154,  167,  805],
       [ 715, 1600,  114, 1461, 1388],
       [ 477,  568, 1805, 1761, 1212],
       [ 529,   41, 1575, 1806, 1177],
       [1719, 1338,  993,  444,  251],
       [ 666, 1270, 1126, 1320,  606]])

In [ ]:
m_arr[:,2:]

In [172]:
m_arr[:,2:] = 100
m_arr

array([[1664,  675,  100,  100,  100],
       [1122,   37,  100,  100,  100],
       [1477, 1582,  100,  100,  100],
       [ 715, 1600,  100,  100,  100],
       [ 477,  568,  100,  100,  100],
       [ 529,   41,  100,  100,  100],
       [1719, 1338,  100,  100,  100],
       [ 666, 1270,  100,  100,  100]])

In [173]:
m_arr[:] = 45
m_arr

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]])

### reikšmių paėmimas pagal sąlygą

In [150]:
arr

array([ 0, 40, 66, 66, 66, 66, 66, 66,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [151]:
bool_arr = arr < 40
bool_arr

array([ True, False, False, False, False, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [152]:
arr[bool_arr]

array([ 0,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [153]:
arr[arr > 15]

array([40, 66, 66, 66, 66, 66, 66, 16, 17, 18, 19])

### įpatumai

In [177]:
arr_int_rand = np.random.randint(10, 2000, 40)
m_arr = arr_int_rand.reshape(8, -1)
m_arr

array([[1168, 1807, 1295,  989,  540],
       [1889,  767, 1058, 1557,  652],
       [1481,  665, 1589, 1835, 1045],
       [ 196,  789, 1282,  837,  362],
       [1832, 1156, 1928, 1371,  868],
       [1415, 1916, 1868, 1951,  216],
       [1356,  254,  787,  612,  820],
       [1638,  910, 1654,  384, 1711]])

In [178]:
slice_m_arr = m_arr[1:-1, 1:3]
slice_m_arr

array([[ 767, 1058],
       [ 665, 1589],
       [ 789, 1282],
       [1156, 1928],
       [1916, 1868],
       [ 254,  787]])

In [179]:
slice_m_arr[:] = 777
slice_m_arr

array([[777, 777],
       [777, 777],
       [777, 777],
       [777, 777],
       [777, 777],
       [777, 777]])

In [180]:
m_arr

array([[1168, 1807, 1295,  989,  540],
       [1889,  777,  777, 1557,  652],
       [1481,  777,  777, 1835, 1045],
       [ 196,  777,  777,  837,  362],
       [1832,  777,  777, 1371,  868],
       [1415,  777,  777, 1951,  216],
       [1356,  777,  777,  612,  820],
       [1638,  910, 1654,  384, 1711]])

In [181]:
slice_m_arr = m_arr[1:-1, 1:3]
slice_m_arr = slice_m_arr.copy()

In [183]:
slice_m_arr[:] = 999
slice_m_arr

array([[999, 999],
       [999, 999],
       [999, 999],
       [999, 999],
       [999, 999],
       [999, 999]])

In [184]:
m_arr

array([[1168, 1807, 1295,  989,  540],
       [1889,  777,  777, 1557,  652],
       [1481,  777,  777, 1835, 1045],
       [ 196,  777,  777,  837,  362],
       [1832,  777,  777, 1371,  868],
       [1415,  777,  777, 1951,  216],
       [1356,  777,  777,  612,  820],
       [1638,  910, 1654,  384, 1711]])

In [185]:
arr

array([ 0, 40, 66, 66, 66, 66, 66, 66,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [186]:
arr_int_rand

array([1168, 1807, 1295,  989,  540, 1889,  777,  777, 1557,  652, 1481,
        777,  777, 1835, 1045,  196,  777,  777,  837,  362, 1832,  777,
        777, 1371,  868, 1415,  777,  777, 1951,  216, 1356,  777,  777,
        612,  820, 1638,  910, 1654,  384, 1711])

### aritmetiniai veiksmai

In [187]:
arr

array([ 0, 40, 66, 66, 66, 66, 66, 66,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [188]:
arr + arr

array([  0,  80, 132, 132, 132, 132, 132, 132,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38])

In [189]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [190]:
arr * arr

array([   0, 1600, 4356, 4356, 4356, 4356, 4356, 4356,   64,   81,  100,
        121,  144,  169,  196,  225,  256,  289,  324,  361])

In [191]:
arr / arr

C:\Users\CodeAcademy\AppData\Local\Temp\ipykernel_20236\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [192]:
arr / 0

C:\Users\CodeAcademy\AppData\Local\Temp\ipykernel_20236\3942562399.py:1: RuntimeWarning: divide by zero encountered in divide
  arr / 0
C:\Users\CodeAcademy\AppData\Local\Temp\ipykernel_20236\3942562399.py:1: RuntimeWarning: invalid value encountered in divide
  arr / 0


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf,
       inf, inf, inf, inf, inf, inf, inf])

In [193]:
arr + 1000

array([1000, 1040, 1066, 1066, 1066, 1066, 1066, 1066, 1008, 1009, 1010,
       1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019])

In [194]:
arr * 5

array([  0, 200, 330, 330, 330, 330, 330, 330,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95])

In [195]:
arr ** 5

array([         0,  102400000, 1252332576, 1252332576, 1252332576,
       1252332576, 1252332576, 1252332576,      32768,      59049,
           100000,     161051,     248832,     371293,     537824,
           759375,    1048576,    1419857,    1889568,    2476099],
      dtype=int32)

In [196]:
np.sin(arr)

array([ 0.        ,  0.74511316, -0.02655115, -0.02655115, -0.02655115,
       -0.02655115, -0.02655115, -0.02655115,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [197]:
np.log(arr)

C:\Users\CodeAcademy\AppData\Local\Temp\ipykernel_20236\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 3.68887945, 4.18965474, 4.18965474, 4.18965474,
       4.18965474, 4.18965474, 4.18965474, 2.07944154, 2.19722458,
       2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
       2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [198]:
np.sqrt(arr)

array([0.        , 6.32455532, 8.1240384 , 8.1240384 , 8.1240384 ,
       8.1240384 , 8.1240384 , 8.1240384 , 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894])